### PR TITLE
README.md: Neovim now supports focus events

### PR DESCRIPTION
**Pull request by ghost**
refs https://github.com/neovim/neovim/pull/3488

### CODE REVIEW

**Comment by bruno-** [comment]
I think the info it works with neovim (and this plugin is not required) and from which version number would be much more useful info.

**Comment by ghost** [comment]
> I think the info it works with neovim (and this plugin is not required) and from which version number would be much more useful info.

Sure, I added that, but what do you mean that this plugin is not required? Without this plugin, Neovim doesn't automatically reload files if they change.

**Comment by bruno-** [comment]
Hmm.. you're right about the `autoread` feature. However, you can now get that in NeoVim with this one-liner:

```
au FocusGained * if &autoread | silent checktime | endif
```

Okay, it's not really a one liner: the special handling for reloading files when the cursor is in vim's command line is missing..

Still I think NeoVim users should not need this plugin anymore, because its main focus is restoring `FocusGained` and `FocusLost` for vim within tmux.
Thoughts?

You wanna test and be a maintainer of a neovim-only plugin if we extracted the `autoread` feature out?

**Comment by ghost** [comment]
> Still I think NeoVim users should not need this plugin anymore, because its main focus is restoring FocusGained and FocusLost for vim within tmux.
> Thoughts?

I think you're right. I've just replaced the use of this plugin in my config with that one-liner you provided (thanks!).

> You wanna test and be a maintainer of a neovim-only plugin if we extracted the autoread feature out?

The aforementioned one-liner works for the vast majority of use cases I have, so no thanks.

**Comment by ghost** [comment]
If you want, I can update this PR to add a notice saying something like "Neovim users don't need this plugin, use this autocmd instead".

**Pull request closed without merging**
