### PR TITLE
Update README to reflect NeoVim support and test on st

### PR DESCRIPTION
**Pull request by mlopes**
I've tested it in NeoVim and it works (as expected after this having been merged https://github.com/neovim/neovim/pull/3488), also the test was done in [st (simple terminal)](https://st.suckless.org/), and I can confirm that it worked.

### CODE REVIEW

**Comment by bruno-** [comment]
Why not indicate neovim is supported?

**Comment by mlopes** [comment]
Might be worth, idk, most plugins don’t state that specifically, and I as a neovim user tend to assume the plugin works in neovim unless stated otherwise, but in this case since it was in the readme for a long time saying it didn’t it, it might be worth it.

**Comment by mlopes** [comment]
Ok, done, added a mention that it works on both.

**Comment by bruno-** [comment]
Thanks

**Pull request merged**
